### ISSUE TITLE
Automatically detect glslang-tools package

### ISSUE THREAD

**Issue by thomasbbrunner** [cadenasgmbh/vscode-glsllint#10]
Since Ubuntu 19.04 and Debian Buster, the glslang-tools package can be installed from the official PPAs. This package contains the glslangValidator executable.

It would be nice to add this to the documentation, as it makes installation simpler. 

Moreover, the extension could automatically look for the executable in the Linux binaries folder (standard installation path of the glslandValidator executable), similar to what other VS Code extensions do.

**Comment by hsimpson** [comment]
It does not work in Windows see https://github.com/cadenasgmbh/vscode-glsllint/issues/15#issuecomment-613097788
