### ISSUE TITLE
Elm support

### ISSUE THREAD

**Issue by Razzeee** [cadenasgmbh/vscode-glsllint#14]
Hey, 

elm supports inline glsl like this https://github.com/johnpmayer/elm-webgl/blob/master/examples/crate.elm#L101-L113

I pretty much was brought here by the new documentation from MS about embedded languages https://code.visualstudio.com/api/language-extensions/embedded-languages

I already detect glsl in https://github.com/elm-tooling/elm-language-server but do nothing with it. Seeing that you support js etc inline, could the same be done for elm?

Cheers

**Comment by hsimpson** [comment]
Hm good question. I have to take a deeper look into this, I have no knowledge about Elm.

The JS/TS Inline feature is done with the ts parser which give me access to the AST of JS/TS

**Comment by hsimpson** [comment]
Because I have no knowledge about Elm, in your example: 
```elm
vertexShader = [glsl|
attribute vec3 pos;
attribute vec3 coord;
uniform mat4 perspective;
varying vec2 vcoord;
void main () {
  gl_Position = perspective * vec4(pos, 1.0);
  vcoord = coord.xy;
}
|]
```
Is this elm specific: `[glsl|...|]`? Is there a mark or something which declares an vertex or fragment shader?

**Comment by Razzeee** [comment]
I'm not very

**Comment by w0rm** [comment]
Elm does not have any special syntax to distinguish between fragment and vertex shaders.

This is a simple example of embedded glsl blocks: https://github.com/elm-explorations/webgl/blob/master/examples/triangle.elm#L77

**Comment by hsimpson** [comment]
Ok then I think the best way will be to define a list of Regex for each language like Elm or other languages.
