### ISSUE TITLE
Errors lingering in the file and problems section when fixed

### ISSUE THREAD

**Issue by linvogel** [cadenasgmbh/vscode-glsllint#17]
Whenever I make a mistake in the glsl code, it gets reported as I would expect when saving the file (lets say, i forgot a semicolon, it marks the error with the typical red underline and reports it in the Problems tab).
But when I fix it and save again, the report stays in the Problems tab of VS Code and a small rest (only about the width of a single character) of the typical red underline remains, usually on the next line. 

The only way I could fix this up until now is closing the file, open it again, and save it again to be sure the code was indeed correct this time. I suspect that this is not supposed to happen, as it is sort of distracting/irritating when the file actually is correct.

**Comment by hsimpson** [comment]
Could you provide a animated GIF or Video to describe your problem?

**Comment by hsimpson** [comment]
> 
> 
> Could you provide a animated GIF or Video to describe your problem?

Forget about it, I could reproduce it.
