### ISSUE TITLE
Building error when rgen rmiss rchit shaders

### ISSUE THREAD

**Issue by Reon90** [cadenasgmbh/vscode-glsllint#7]
I always see `Wrong parameters when starting glslangValidator. Arguments: --stdin -S unkown` when try to edit .rmiss .rchit .rgen shaders. Could you check or throw correct error message?

**Comment by hsimpson** [comment]
@Reon90 it looks like I have not implemented the support for the raytracing shaders right now.
I will improve the extension to stage mapping, so it can be configured via extension settings.

**Comment by W4RH4WK** [comment]
I think the extension worked for ray tracing shaders in the past. I believe 30c9c21 broke it by always providing `-S` as commandline argument.

@hsimpson can you try omitting the `-S` if the shader stage is unknown. This way the command shouldn't error immediately and provide at least *some* useful output.

**Comment by hsimpson** [comment]
@W4RH4WK: no because I have switched from temp files to stdin write to glslangValidator executable. Which is a bit more flexible to handle, but forgot to map all possible shader formats. But a fix is right around the corner.

**Comment by W4RH4WK** [comment]
Just updated the extension, it now works perfectly again. Thank you very  much.
