### ISSUE TITLE
Got error on validating simple glsl file

### ISSUE THREAD

**Issue by ck33122** [cadenasgmbh/vscode-glsllint#8]
I download and unzip latest version of glslang from KhronosGroup github (file glslang-master-windows-x64-Release.zip). I unzipped it into 'C:\Program Files\GLSLValidator' folder. In VSCode I configured path to executable: 
```
  "glsllint.glslangValidatorPath": "C:\\Program Files\\GLSLValidator\\bin\\glslangValidator.exe"
```
After opening folder with my code I got error:
```
Wrong parameters when starting glslangValidator.
Arguments: --stdin -S unkown
```
I dont know what it means. I never install vscode-glsllint extension before. I use Windows 10 and VSCode 1.39.2.

Please help me to setup it correctly.
Sorry for my English, I'm Russian.

**Comment by DenisAloner** [comment]
The following helped me: change the extension of the vertex shader file to ".vert" and he extension of the vertex shader file to ".frag". You can read more about it [here](https://github.com/KhronosGroup/glslang).
  Note that the file is checked when it is saved, not on the fly.
  P.S.: Sorry for my English, I'm Russian too.

**Comment by ck33122** [comment]
> The following helped me: change the extension of the vertex shader file to ".vert" and the extension of the fragment shader file to ".frag".

Thanks. Это помогло.

**Comment by hsimpson** [comment]
May be I will add a file extension check into the extension. As @DenisAloner wrote the glslvalidator is a bit restricted according to file extensions.
