### ISSUE TITLE
How do i use this?

### ISSUE THREAD

**Issue by DusanBosnjakKodiak** [cadenasgmbh/vscode-glsllint#9]
I've installed the two extensions and pointed this one to the glsl validator. Nothing happens in my vscode, other than getting a notification:
> There is no formatter for 'glsl' files installed. 

What am i doing wrong?

**Comment by hsimpson** [comment]
vscode-glsllint is no formatter, which does code formatting but it could check your code for syntax errors.

After you have configured vscode-glsllint probably, you can lint your shader files when saving.
